export default () => [
    { recept_Id: 0, name: 'lounglers', qantity: 2 },
    { recept_Id: 0, name: 'sugar', qantity: 1 },
    { recept_Id: 0, name: 'tomatoes', qantity: 2 },
    { recept_Id: 1, name: 'potatoes', qantity: '600 g' },
    { recept_Id: 1, name: 'milk', qantity: '300 ml' },
    { recept_Id: 1, name: 'garlic', qantity: '4 prongs' },
    { recept_Id: 2, name: 'fillet cray', qantity: '1.2 kg' },
    { recept_Id: 2, name: 'lemon', qantity: 2 },
    { recept_Id: 2, name: 'parsley', qantity: '120 g' },
    { recept_Id: 3, name: 'cherry tomatoes', qantity: 24 },
    { recept_Id: 3, name: 'hake', qantity: 4 },
    { recept_Id: 3, name: 'garlic', qantity: '3 prongs' },
    { recept_Id: 4, name: 'whole bird', qantity: '3 tablespoons' },
    { recept_Id: 4, name: 'beef', qantity: '1 kg' },
    { recept_Id: 4, name: 'garlic', qantity: '4 prongs' },
    { recept_Id: 5, name: 'parsley', qantity: '20 g' },
    { recept_Id: 5, name: 'round ris', qantity: '300 g' },
    { recept_Id: 5, name: 'tomatoes', qantity: 2 },
    { recept_Id: 6, name: 'shrimp', qantity: '200 g' },
    { recept_Id: 6, name: 'pumpkin', qantity: '300 g' },
    { recept_Id: 6, name: 'paste fettuchini', qantity: '500 g' },
    { recept_Id: 6, name: 'chapmignon', qantity: '200 g' },
    { recept_Id: 7, name: 'cherry tomatoes', qantity: 24 },
    { recept_Id: 7, name: 'garlic', qantity: '4 prongs' },
    { recept_Id: 7, name: 'potatoes', qantity: '600 g' }
];